"""Data models package."""

from app.models.agent_state import ExtractedPlantEntities, PlantCareState
from app.models.api_schemas import (
    ChatRequest,
    ChatResponse,
    EventLogCreateRequest,
    EventLogResponse,
    PhaseSummaryResponse,
    PlantCreateRequest,
    PlantResponse,
    PlantUpdateRequest,
    SpeciesSummaryResponse,
    SubstrateSummaryResponse,
    TraitSummaryResponse,
    UnsupportedSpeciesResponse,
)
from app.models.db_models import (
    ChatMessage,
    ChatSession,
    PlantEventLog,
    UnsupportedSpeciesRequest,
    UserPlant,
)
from app.models.knowledge_base import (
    BaseFeedingModel,
    BotanicalInfoModel,
    CompatibilityStatus,
    GlobalPhasesModel,
    GlobalSubstratesModel,
    GlobalTraitsModel,
    HumidityToleranceModel,
    IdealMixModel,
    LightToleranceModel,
    PhaseFertilizerRulesModel,
    PhaseModel,
    PhaseWateringRulesModel,
    PhenologyConstraintModel,
    SpeciesModel,
    SubstrateCompatibilityRuleModel,
    SubstrateModel,
    SubstrateRequirementsModel,
    SupplementModel,
    TempToleranceModel,
    TolerancesModel,
    TraitEnvAdjustmentsModel,
    TraitFertilizerRulesModel,
    TraitModel,
)

__all__ = [
    # API Schemas
    "ChatRequest",
    "ChatResponse",
    "PlantCreateRequest",
    "PlantUpdateRequest",
    "PlantResponse",
    "EventLogCreateRequest",
    "EventLogResponse",
    "SpeciesSummaryResponse",
    "SubstrateSummaryResponse",
    "TraitSummaryResponse",
    "PhaseSummaryResponse",
    "UnsupportedSpeciesResponse",
    # Agent State Models
    "ExtractedPlantEntities",
    "PlantCareState",
    # DB Models
    "UserPlant",
    "PlantEventLog",
    "ChatSession",
    "ChatMessage",
    "UnsupportedSpeciesRequest",
    # Knowledge Base Models
    "CompatibilityStatus",
    "SupplementModel",
    "LightToleranceModel",
    "HumidityToleranceModel",
    "TempToleranceModel",
    "TolerancesModel",
    "BotanicalInfoModel",
    "BaseFeedingModel",
    "IdealMixModel",
    "SubstrateCompatibilityRuleModel",
    "SubstrateRequirementsModel",
    "PhenologyConstraintModel",
    "SpeciesModel",
    "SubstrateModel",
    "GlobalSubstratesModel",
    "TraitFertilizerRulesModel",
    "TraitEnvAdjustmentsModel",
    "TraitModel",
    "GlobalTraitsModel",
    "PhaseFertilizerRulesModel",
    "PhaseWateringRulesModel",
    "PhaseModel",
    "GlobalPhasesModel",
]
